// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQtLbMZd4xzokCapUzq8rMuQADN3MaZ90',
    appId: '1:845593034244:web:b8c1eb37f3ff431d62ff51',
    messagingSenderId: '845593034244',
    projectId: 'my-product-app-goteri141',
    authDomain: 'my-product-app-goteri141.firebaseapp.com',
    storageBucket: 'my-product-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC08iHmJoS0W86ahw_HYaMy5dMU-0iAprE',
    appId: '1:845593034244:android:8cf12b29beb36baa62ff51',
    messagingSenderId: '845593034244',
    projectId: 'my-product-app-goteri141',
    storageBucket: 'my-product-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRbNwniZ5BW_NkUUpezv4sn3e5HJcZk4',
    appId: '1:845593034244:ios:309af533a19a342c62ff51',
    messagingSenderId: '845593034244',
    projectId: 'my-product-app-goteri141',
    storageBucket: 'my-product-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.myProductApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRbNwniZ5BW_NkUUpezv4sn3e5HJcZk4',
    appId: '1:845593034244:ios:309af533a19a342c62ff51',
    messagingSenderId: '845593034244',
    projectId: 'my-product-app-goteri141',
    storageBucket: 'my-product-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.myProductApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQtLbMZd4xzokCapUzq8rMuQADN3MaZ90',
    appId: '1:845593034244:web:659b41c114e868c062ff51',
    messagingSenderId: '845593034244',
    projectId: 'my-product-app-goteri141',
    authDomain: 'my-product-app-goteri141.firebaseapp.com',
    storageBucket: 'my-product-app-goteri141.firebasestorage.app',
  );
}
